development:
  adapter: postgresql
  encoding: unicode
  database: zapopan_development
  pool: 5
  username: eddie
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: zapopan_test
  pool: 5
  username: eddie
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: zapopan_production
  pool: 5
  username: eddie
  password:
