development:
  adapter: sqlite3
  database: db/zapopan_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/zapopan_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: zapopan_production
  pool: 5
  username: eddie
  password:
